export default {
  ADD_INCOME_MONEY: 'balance/ADD_INCOME_MONEY',
  EDIT_INCOME_MONEY: 'balance/EDIT_INCOME_MONEY',
  REMOVE_INCOME_MONEY: 'balance/REMOVE_INCOME_MONEY',

  ADD_WITHDRAW_MONEY: 'balance/ADD_WITHDRAW_MONEY',
  EDIT_WITHDRAW_MONEY: 'balance/EDIT_WITHDRAW_MONEY',
  REMOVE_WITHDRAW_MONEY: 'balance/REMOVE_WITHDRAW_MONEY',

  ADD_FILTER_BY_DATE: 'balance/ADD_FILTER_BY_DATE',
  DELETE_FILTER_BY_DATE: 'balance/DELETE_FILTER_BY_DATE',
};
