export default {
  ADD_INCOME_MONEY: "balance/ADD_INCOME_MONEY",
  EDIT_INCOME_MONEY: "balance/EDIT_INCOME_MONEY",
  REMOVE_INCOME_MONEY: "balance/REMOVE_INCOME_MONEY",

  ADD_WITHDRAW_MONEY: "balance/ADD_WITHDRAW_MONEY",
  EDIT_WITHDRAW_MONEY: "balance/EDIT_WITHDRAW_MONEY",
  REMOVE_WITHDRAW_MONEY: "balance/REMOVE_WITHDRAW_MONEY"
};
