export default {
  ADD_INCOME_CATEGORY: "categories/ADD_INCOME_CATEGORY",
  EDIT_INCOME_CATEGORY: "categories/EDIT_INCOME_CATEGORY",
  REMOVE_INCOME_CATEGORY: "categories/REMOVE_INCOME_CATEGORY",

  ADD_WITHDRAW_CATEGORY: "categories/ADD_WITHDRAW_CATEGORY",
  EDIT_WITHDRAW_CATEGORY: "categories/ADD_WITHDRAW_CATEGORY",
  REMOVE_WITHDRAW_CATEGORY: "categories/ADD_WITHDRAW_CATEGORY"
};
